POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Testing user ID post",
    "author": "Lupu Alexandru",
    "likes": 111,
    "userId": "5fa12d59d1feda26f01e96eb"
}